name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # setup-go
      - name: set up
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
      # checkout
      - name: checkout
      - uses: actions/checkout@v2
      # test
      - run: go test ./... -v
